"""increase column_name field length to 1000 characters

Revision ID: 1b3e32d81e77
Revises: 55b5e6ecb2a3
Create Date: 2025-06-29 14:49:10.926138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3e32d81e77'
down_revision = '55b5e6ecb2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_label_applications', schema=None) as batch_op:
        batch_op.alter_column('column_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('auto_labels', schema=None) as batch_op:
        batch_op.alter_column('column_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('label_applications', schema=None) as batch_op:
        batch_op.alter_column('column_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('label_generations', schema=None) as batch_op:
        batch_op.alter_column('column_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_admin_flag', ['admin_flag'], unique=False)
        batch_op.create_index('idx_users_email_verified', ['email_verified'], unique=False)
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_users_role', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_role')
        batch_op.drop_index('idx_users_is_active')
        batch_op.drop_index('idx_users_email_verified')
        batch_op.drop_index('idx_users_admin_flag')

    with op.batch_alter_table('label_generations', schema=None) as batch_op:
        batch_op.alter_column('column_name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('label_applications', schema=None) as batch_op:
        batch_op.alter_column('column_name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('auto_labels', schema=None) as batch_op:
        batch_op.alter_column('column_name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('auto_label_applications', schema=None) as batch_op:
        batch_op.alter_column('column_name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###
